name = "Normandy"
license = "MIT"
licenselink = "https://github.com/ooinaruhugh/normandy/blob/main/LICENSE"
description = "A YoRHa-inspired theme for Hugp"
homepage = "https://github.com/ooinaruhugh/normandy"
tags = []
features = []
min_version = "0.60.0"

[author]
  name = "Kamillo Ferry"
  homepage = "http://kafe.dev/"

# If porting an existing theme
[original]
  name = "YoRHa"
  homepage = "https://github.com/metakirby5/yorha"
  repo = "https://github.com/metakirby5/yorha"
  license = "MIT"
  licenselink = "https://github.com/metakirby5/yorha/blob/master/LICENSE"
